In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
 
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_5d524b2b2b784cfa9e9f471796f5b70c = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='UKp78tCowQEgr9EDhVSDi6i58ubCJ11IfD8a3lCq9BmY',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_5d524b2b2b784cfa9e9f471796f5b70c.get_object(Bucket='companyturnover-donotdelete-pr-estm8jy7kqril1',Key='Data_set.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()


Company  R&D Spend  Administration  Marketing Spend    Revenue  Sales  \
0   Maruti  165349.20       136897.80        471784.10  123456.98     12   
1  Hyundai  162597.70       151377.59        443898.53  132567.78     21   
2  Renault  153441.51       101145.55        407934.54  145678.76     14   
3   Maruti  144372.41       118671.85        383199.62  123569.04     12   
4  Hyundai  142107.34        91391.77        366168.42  134576.98     22   

     Turnover  
0  2255514.86  
1  3541797.20  
2  2702024.24  
3  2129072.36  
4  3560361.09

In [4]:
type(dataset)

pandas.core.frame.DataFrame

In [5]:
dataset

Company  R&D Spend  Administration  Marketing Spend    Revenue  Sales  \
0    Maruti  165349.20       136897.80        471784.10  123456.98     12   
1   Hyundai  162597.70       151377.59        443898.53  132567.78     21   
2   Renault  153441.51       101145.55        407934.54  145678.76     14   
3    Maruti  144372.41       118671.85        383199.62  123569.04     12   
4   Hyundai  142107.34        91391.77        366168.42  134576.98     22   
5   Renault  131876.90        99814.71        362861.36  123465.78     32   
6    Maruti  134615.46       147198.87        127716.82  154678.83     34   
7   Hyundai  130298.13       145530.06        323876.68  132345.65     23   
8   Renault  120542.52       148718.95        311613.29  154256.34     12   
9    Maruti  123334.88       108679.17        304981.62  231432.23     14   
10  Hyundai  101913.08       110594.11        229160.95  235647.23     25   
11  Renault  100671.96        91790.61        249744.55  343212.12     23   
12   Maruti   93863.75       127320.38        249839.44  233576.22     12   
13  Hyundai   91992.39       135495.07        252664.93  235664.33     16   
14  Renault  119943.24       156547.42        256512.92  563411.44     32   
15   Maruti  114523.61       122616.84        261776.23  665342.23     15   
16  Hyundai   78013.11       121597.55        264346.06  665341.34     25   
17  Renault   94657.16       145077.58        282574.31  765432.23     32   
18   Maruti   91749.16       114175.79        294919.57  543532.87     41   
19  Hyundai   86419.70       153514.11             0.00  321098.80     68   
20  Renault   76253.86       113867.30        298664.47  423256.32     20   
21   Maruti   78389.47       153773.43        299737.29  887665.22     31   
22  Hyundai   73994.56       122782.75        303319.26  567890.67     22   
23  Renault   67532.53       105751.03        304768.73  546378.66     31   
24   Maruti   77044.01        99281.34        140574.81  345566.37     41   
25  Hyundai   64664.71       139553.16        137962.62  866598.66     25   
26  Renault   75328.87       144135.98        134050.07  877636.44     23   
27   Maruti   72107.60       127864.55        353183.81  988377.43     65   
28  Hyundai   66051.52       182645.56        118148.20  456321.90     34   
29  Renault   65605.48       153032.06        107138.38  654321.98     23   
30   Maruti   61994.48       115641.28         91131.24  564388.88     12   
31  Hyundai   61136.38       152701.92         88218.23  234567.09     18   
32  Renault   63408.86       129219.61         46085.25  682932.98     19   
33   Maruti   55493.95       103057.49        214634.81  784652.44     27   
34  Hyundai   46426.07       157693.92        210797.67  632122.32     26   
35  Renault   46014.02        85047.44        205517.64  783248.44     31   
36   Maruti   28663.76       127056.21        201126.82  937289.56     22   
37  Hyundai   44069.95        51283.14        197029.42  953749.57      8   
38  Renault   20229.59        65947.93        185265.10  542833.43     21   
39   Maruti   38558.51        82982.09        174999.30  761214.43     54   
40  Hyundai   28754.33       118546.05        172795.67  523342.76     43   
41  Renault   27892.92        84710.77        164470.71  327423.54     32   
42   Maruti   23640.93        96189.63        148001.11  765734.34     54   
43  Hyundai   15505.73       127382.30         35534.17  347282.45     12   
44  Renault   22177.74       154806.14         28334.72  534732.43     11   
45   Maruti    1000.23       124153.04          1903.93  347874.43     18   
46  Hyundai    1315.46       115816.21        297114.46  632476.67     34   
47  Renault       0.00       135426.92             0.00  543210.45     22   
48   Maruti     542.05        51743.15             0.00  543217.34     65   
49  Hyundai       0.00       116983.80         45173.06  987654.43     10   

       Turnover  
0    2255514.86  
1    3541797.20  
2    2702024.24  
3   

In [6]:
dataset.head()

Company  R&D Spend  Administration  Marketing Spend    Revenue  Sales  \
0   Maruti  165349.20       136897.80        471784.10  123456.98     12   
1  Hyundai  162597.70       151377.59        443898.53  132567.78     21   
2  Renault  153441.51       101145.55        407934.54  145678.76     14   
3   Maruti  144372.41       118671.85        383199.62  123569.04     12   
4  Hyundai  142107.34        91391.77        366168.42  134576.98     22   

     Turnover  
0  2255514.86  
1  3541797.20  
2  2702024.24  
3  2129072.36  
4  3560361.09

In [7]:
dataset.head(13)

Company  R&D Spend  Administration  Marketing Spend    Revenue  Sales  \
0    Maruti  165349.20       136897.80        471784.10  123456.98     12   
1   Hyundai  162597.70       151377.59        443898.53  132567.78     21   
2   Renault  153441.51       101145.55        407934.54  145678.76     14   
3    Maruti  144372.41       118671.85        383199.62  123569.04     12   
4   Hyundai  142107.34        91391.77        366168.42  134576.98     22   
5   Renault  131876.90        99814.71        362861.36  123465.78     32   
6    Maruti  134615.46       147198.87        127716.82  154678.83     34   
7   Hyundai  130298.13       145530.06        323876.68  132345.65     23   
8   Renault  120542.52       148718.95        311613.29  154256.34     12   
9    Maruti  123334.88       108679.17        304981.62  231432.23     14   
10  Hyundai  101913.08       110594.11        229160.95  235647.23     25   
11  Renault  100671.96        91790.61        249744.55  343212.12     23   
12   Maruti   93863.75       127320.38        249839.44  233576.22     12   

      Turnover  
0   2255514.86  
1   3541797.20  
2   2702024.24  
3   2129072.36  
4   3560361.09  
5   4545457.93  
6   5668611.37  
7   3643654.82  
8   2431950.84  
9   3777046.89  
10  6332848.89  
11  8336085.88  
12  3273938.21

Step3- Split Independent and Dpendent Variables

In [8]:
x= dataset.iloc[:,:6]

In [9]:
x

Company  R&D Spend  Administration  Marketing Spend    Revenue  Sales
0    Maruti  165349.20       136897.80        471784.10  123456.98     12
1   Hyundai  162597.70       151377.59        443898.53  132567.78     21
2   Renault  153441.51       101145.55        407934.54  145678.76     14
3    Maruti  144372.41       118671.85        383199.62  123569.04     12
4   Hyundai  142107.34        91391.77        366168.42  134576.98     22
5   Renault  131876.90        99814.71        362861.36  123465.78     32
6    Maruti  134615.46       147198.87        127716.82  154678.83     34
7   Hyundai  130298.13       145530.06        323876.68  132345.65     23
8   Renault  120542.52       148718.95        311613.29  154256.34     12
9    Maruti  123334.88       108679.17        304981.62  231432.23     14
10  Hyundai  101913.08       110594.11        229160.95  235647.23     25
11  Renault  100671.96        91790.61        249744.55  343212.12     23
12   Maruti   93863.75       127320.38        249839.44  233576.22     12
13  Hyundai   91992.39       135495.07        252664.93  235664.33     16
14  Renault  119943.24       156547.42        256512.92  563411.44     32
15   Maruti  114523.61       122616.84        261776.23  665342.23     15
16  Hyundai   78013.11       121597.55        264346.06  665341.34     25
17  Renault   94657.16       145077.58        282574.31  765432.23     32
18   Maruti   91749.16       114175.79        294919.57  543532.87     41
19  Hyundai   86419.70       153514.11             0.00  321098.80     68
20  Renault   76253.86       113867.30        298664.47  423256.32     20
21   Maruti   78389.47       153773.43        299737.29  887665.22     31
22  Hyundai   73994.56       122782.75        303319.26  567890.67     22
23  Renault   67532.53       105751.03        304768.73  546378.66     31
24   Maruti   77044.01        99281.34        140574.81  345566.37     41
25  Hyundai   64664.71       139553.16        137962.62  866598.66     25
26  Renault   75328.87       144135.98        134050.07  877636.44     23
27   Maruti   72107.60       127864.55        353183.81  988377.43     65
28  Hyundai   66051.52       182645.56        118148.20  456321.90     34
29  Renault   65605.48       153032.06        107138.38  654321.98     23
30   Maruti   61994.48       115641.28         91131.24  564388.88     12
31  Hyundai   61136.38       152701.92         88218.23  234567.09     18
32  Renault   63408.86       129219.61         46085.25  682932.98     19
33   Maruti   55493.95       103057.49        214634.81  784652.44     27
34  Hyundai   46426.07       157693.92        210797.67  632122.32     26
35  Renault   46014.02        85047.44        205517.64  783248.44     31
36   Maruti   28663.76       127056.21        201126.82  937289.56     22
37  Hyundai   44069.95        51283.14        197029.42  953749.57      8
38  Renault   20229.59        65947.93        185265.10  542833.43     21
39   Maruti   38558.51        82982.09        174999.30  761214.43     54
40  Hyundai   28754.33       118546.05        172795.67  523342.76     43
41  Renault   27892.92        84710.77        164470.71  327423.54     32
42   Maruti   23640.93        96189.63        148001.11  765734.34     54
43  Hyundai   15505.73       127382.30         35534.17  347282.45     12
44  Renault   22177.74       154806.14         28334.72  534732.43     11
45   Maruti    1000.23       124153.04          1903.93  347874.43     18
46  Hyundai    1315.46       115816.21        297114.46  632476.67     34
47  Renault       0.00       135426.92             0.00  543210.45     22
48   Maruti     542.05        51743.15             0.00  543217.34     65
49  Hyundai       0.00       116983.80         45173.06  987654.43     10

In [10]:
type(x)

pandas.core.frame.DataFrame

In [11]:
x= dataset.iloc[:,:6].values #convert from dataframe to numpy array

In [12]:
x

array([['Maruti', 165349.2, 136897.8, 471784.1, 123456.98, 12],
       ['Hyundai', 162597.7, 151377.59, 443898.53, 132567.78, 21],
       ['Renault', 153441.51, 101145.55, 407934.54, 145678.76, 14],
       ['Maruti', 144372.41, 118671.85, 383199.62, 123569.04, 12],
       ['Hyundai', 142107.34, 91391.77, 366168.42, 134576.98, 22],
       ['Renault', 131876.9, 99814.71, 362861.36, 123465.78, 32],
       ['Maruti', 134615.46, 147198.87, 127716.82, 154678.83, 34],
       ['Hyundai', 130298.13, 145530.06, 323876.68, 132345.65, 23],
       ['Renault', 120542.52, 148718.95, 311613.29, 154256.34, 12],
       ['Maruti', 123334.88, 108679.17, 304981.62, 231432.23, 14],
       ['Hyundai', 101913.08, 110594.11, 229160.95, 235647.23, 25],
       ['Renault', 100671.96, 91790.61, 249744.55, 343212.12, 23],
       ['Maruti', 93863.75, 127320.38, 249839.44, 233576.22, 12],
       ['Hyundai', 91992.39, 135495.07, 252664.93, 235664.33, 16],
       ['Renault', 119943.24, 156547.42, 256512.92, 563411.44, 

In [13]:
x.ndim #mandatory to be in 2 dimesion for Linear Regression

2

In [14]:
type(x)

numpy.ndarray

In [15]:
y= dataset.iloc[:,-1:]

In [16]:
y.shape

(50, 1)

In [17]:
y

Turnover
0    2255514.86
1    3541797.20
2    2702024.24
3    2129072.36
4    3560361.09
5    4545457.93
6    5668611.37
7    3643654.82
8    2431950.84
9    3777046.89
10   6332848.89
11   8336085.88
12   3273938.21
13   4250781.67
14  18562169.66
15  10479050.13
16  17097490.22
17  25016140.41
18  22785692.19
19  22074652.21
20   8953912.03
21  28049522.01
22  12993691.31
23  17415790.75
24  14485121.33
25  22007146.99
26  20539153.04
27  64797688.91
28  15881789.88
29  15375181.46
30   7041433.56
31   4524264.15
32  13214440.34
33  21558802.13
34  16850097.98
35  24617280.74
36  20977217.11
37   7922379.07
38  11670944.65
39  41402119.12
40  22823834.73
41  10754627.68
42  41617486.03
43   4345811.60
44   6087375.33
45   6388796.94
46  21918452.91
47  12086056.82
48  35361412.30
49  10038701.16

In [18]:
y= dataset.iloc[:,-1:].values

In [19]:
y

array([[  2255514.86],
       [  3541797.2 ],
       [  2702024.24],
       [  2129072.36],
       [  3560361.09],
       [  4545457.93],
       [  5668611.37],
       [  3643654.82],
       [  2431950.84],
       [  3777046.89],
       [  6332848.89],
       [  8336085.88],
       [  3273938.21],
       [  4250781.67],
       [ 18562169.66],
       [ 10479050.13],
       [ 17097490.22],
       [ 25016140.41],
       [ 22785692.19],
       [ 22074652.21],
       [  8953912.03],
       [ 28049522.01],
       [ 12993691.31],
       [ 17415790.75],
       [ 14485121.33],
       [ 22007146.99],
       [ 20539153.04],
       [ 64797688.91],
       [ 15881789.88],
       [ 15375181.46],
       [  7041433.56],
       [  4524264.15],
       [ 13214440.34],
       [ 21558802.13],
       [ 16850097.98],
       [ 24617280.74],
       [ 20977217.11],
       [  7922379.07],
       [ 11670944.65],
       [ 41402119.12],
       [ 22823834.73],
       [ 10754627.68],
       [ 41617486.03],
       [  4

Step5-Encode categorical Text Variables

In [20]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [21]:
x[:,0]=lb.fit_transform(x[:,0])

In [22]:
x

array([[1, 165349.2, 136897.8, 471784.1, 123456.98, 12],
       [0, 162597.7, 151377.59, 443898.53, 132567.78, 21],
       [2, 153441.51, 101145.55, 407934.54, 145678.76, 14],
       [1, 144372.41, 118671.85, 383199.62, 123569.04, 12],
       [0, 142107.34, 91391.77, 366168.42, 134576.98, 22],
       [2, 131876.9, 99814.71, 362861.36, 123465.78, 32],
       [1, 134615.46, 147198.87, 127716.82, 154678.83, 34],
       [0, 130298.13, 145530.06, 323876.68, 132345.65, 23],
       [2, 120542.52, 148718.95, 311613.29, 154256.34, 12],
       [1, 123334.88, 108679.17, 304981.62, 231432.23, 14],
       [0, 101913.08, 110594.11, 229160.95, 235647.23, 25],
       [2, 100671.96, 91790.61, 249744.55, 343212.12, 23],
       [1, 93863.75, 127320.38, 249839.44, 233576.22, 12],
       [0, 91992.39, 135495.07, 252664.93, 235664.33, 16],
       [2, 119943.24, 156547.42, 256512.92, 563411.44, 32],
       [1, 114523.61, 122616.84, 261776.23, 665342.23, 15],
       [0, 78013.11, 121597.55, 264346.06, 665341.

In [23]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(categorical_features=[0])#categorical Features represents which column to be onehot encoded
x=oh.fit_transform(x).toarray()

In [24]:
x

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.65349200e+05,   1.36897800e+05,   4.71784100e+05,
          1.23456980e+05,   1.20000000e+01],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.62597700e+05,   1.51377590e+05,   4.43898530e+05,
          1.32567780e+05,   2.10000000e+01],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.53441510e+05,   1.01145550e+05,   4.07934540e+05,
          1.45678760e+05,   1.40000000e+01],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.44372410e+05,   1.18671850e+05,   3.83199620e+05,
          1.23569040e+05,   1.20000000e+01],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.42107340e+05,   9.13917700e+04,   3.66168420e+05,
          1.34576980e+05,   2.20000000e+01],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.31876900e+05,   9.98147100e+04,   3.62861360e+05,
          1.23465780e+05,   3.2

In [25]:
x=x[:,1:] #Removing Dummy variable (removing the column which is not required .so removing first column)

In [26]:
x

array([[  1.00000000e+00,   0.00000000e+00,   1.65349200e+05,
          1.36897800e+05,   4.71784100e+05,   1.23456980e+05,
          1.20000000e+01],
       [  0.00000000e+00,   0.00000000e+00,   1.62597700e+05,
          1.51377590e+05,   4.43898530e+05,   1.32567780e+05,
          2.10000000e+01],
       [  0.00000000e+00,   1.00000000e+00,   1.53441510e+05,
          1.01145550e+05,   4.07934540e+05,   1.45678760e+05,
          1.40000000e+01],
       [  1.00000000e+00,   0.00000000e+00,   1.44372410e+05,
          1.18671850e+05,   3.83199620e+05,   1.23569040e+05,
          1.20000000e+01],
       [  0.00000000e+00,   0.00000000e+00,   1.42107340e+05,
          9.13917700e+04,   3.66168420e+05,   1.34576980e+05,
          2.20000000e+01],
       [  0.00000000e+00,   1.00000000e+00,   1.31876900e+05,
          9.98147100e+04,   3.62861360e+05,   1.23465780e+05,
          3.20000000e+01],
       [  1.00000000e+00,   0.00000000e+00,   1.34615460e+05,
          1.47198870e+05,   1.27

In [27]:
from sklearn.model_selection import train_test_split                #previously cros_validation was used in sklearn
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)

In [28]:
x_test.shape

(5, 7)

In [29]:
import keras #Building neural network model back end it has tensorflow
from keras.models import Sequential # initializing model
from keras.layers import Dense # used for adding the neural network layers

Using TensorFlow backend.


In [30]:
model=Sequential()#instance

In [31]:
model.add(Dense(input_dim=7,init="random_uniform",activation="relu",output_dim=4)) #input_dim=no of neurons to have in the input layer(no of independent variables),init=adding weights,activation function,output_dim=next hidden layer
#best thing for output_dim is input_dim/2

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=7, activation="relu", units=4, kernel_initializer="random_uniform")`
  if __name__ == '__main__':


In [32]:
model.add(Dense(output_dim=4,init="random_uniform",activation="relu"))# adding hidden layer similary like adding weights

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=4, kernel_initializer="random_uniform")`
  if __name__ == '__main__':


In [33]:
model.add(Dense(output_dim=1,init="random_uniform"))#adding output layer

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="random_uniform", units=1)`
  if __name__ == '__main__':


In [34]:
model.compile(optimizer='adam',loss='mse',metrics=['mse'])#adam=batch gradent descent

In [35]:
model.fit(x_train,y_train,epochs=1000,batch_size=10)#epochs no of iteration 

Epoch 1/1000
45/45 [==============================] - 0s 5ms/step - loss: 393311182738773.3750 - mean_squared_error: 393311182738773.3750
Epoch 2/1000
45/45 [==============================] - 0s 183us/step - loss: 393310493008782.2500 - mean_squared_error: 393310493008782.2500
Epoch 3/1000
45/45 [==============================] - 0s 186us/step - loss: 393309363342904.8750 - mean_squared_error: 393309363342904.8750
Epoch 4/1000
45/45 [==============================] - 0s 187us/step - loss: 393307920502328.8750 - mean_squared_error: 393307920502328.8750
Epoch 5/1000
45/45 [==============================] - 0s 182us/step - loss: 393305471028792.8750 - mean_squared_error: 393305471028792.8750
Epoch 6/1000
45/45 [==============================] - 0s 185us/step - loss: 393302405924636.5000 - mean_squared_error: 393302405924636.5000
Epoch 7/1000
45/45 [==============================] - 0s 172us/step - loss: 393295840906808.8750 - mean_squared_error: 393295840906808.8750
Epoch 8/1000
45/45 [==

In [36]:
x_test

array([[  0.00000000e+00,   0.00000000e+00,   6.60515200e+04,
          1.82645560e+05,   1.18148200e+05,   4.56321900e+05,
          3.40000000e+01],
       [  0.00000000e+00,   1.00000000e+00,   1.00671960e+05,
          9.17906100e+04,   2.49744550e+05,   3.43212120e+05,
          2.30000000e+01],
       [  0.00000000e+00,   0.00000000e+00,   1.01913080e+05,
          1.10594110e+05,   2.29160950e+05,   2.35647230e+05,
          2.50000000e+01],
       [  0.00000000e+00,   1.00000000e+00,   2.78929200e+04,
          8.47107700e+04,   1.64470710e+05,   3.27423540e+05,
          3.20000000e+01],
       [  0.00000000e+00,   1.00000000e+00,   1.53441510e+05,
          1.01145550e+05,   4.07934540e+05,   1.45678760e+05,
          1.40000000e+01]])

In [37]:
model.predict(x_test)

array([[ 13281194. ],
       [ 10413677. ],
       [  7188309.5],
       [ 10310158. ],
       [  5200565.5]], dtype=float32)

In [38]:
y_test

array([[ 15881789.88],
       [  8336085.88],
       [  6332848.89],
       [ 10754627.68],
       [  2702024.24]])

In [39]:
g=np.array([[0,1,100908,72890.0,676544,1233545,12]])

In [40]:
g.shape

(1, 7)

In [41]:
model.predict(g)

array([[ 38996448.]], dtype=float32)

In [43]:
model.save("mymodel1.h5")
get_ipython().system(u'tar -zcvf mymodel.tgz mymodel1.h5')

mymodel1.h5


In [44]:
!pip install watson_machine_learning_client --upgrade

Requirement already up-to-date: watson_machine_learning_client in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (1.0.365)
Requirement not upgraded as not directly required: certifi in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson_machine_learning_client) (2019.3.9)
Requirement not upgraded as not directly required: ibm-cos-sdk in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson_machine_learning_client) (2.0.1)
Requirement not upgraded as not directly required: tqdm in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson_machine_learning_client) (4.19.5)
Requirement not upgraded as not directly required: requests in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson_machine_learning_client) (2.18.4)
Requirement not upgraded as not directly required: urllib3 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson_machine_learning_client) (1.22)
Requirement not upgraded as not dire

In [45]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient
#to save this model in machine learning service, this is a connection

wml_credentials={
    "url":"https://eu-gb.ml.cloud.ibm.com",
    "access_key":"SHy0tWXWLE7NQyIZb_6KoyWJQBAUUOkdWHE7ljI43Tug",
    "username":"61c2fe9e-f71e-4806-a191-a62b26c8f0dd",
    "password":"ed6e3343-8f23-43f3-98ca-bfc8e106df18",
    "instance_id":"921b4e0f-5957-4d27-aee4-ebc3a5d70714"
}

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [46]:
client = WatsonMachineLearningAPIClient( wml_credentials )

In [47]:
#properties of client
metadata = {
    client.repository.ModelMetaNames.NAME: "keras model",
    client.repository.ModelMetaNames.FRAMEWORK_NAME: "tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES:[{'name':'keras','version':'2.1.3'}],
    client.repository.ModelMetaNames.FRAMEWORK_VERSION: "1.5"
}

In [48]:
model_details = client.repository.store_model( model="mymodel.tgz", meta_props=metadata )

In [49]:
model_id = model_details["metadata"]["guid"]
model_deployment_details = client.deployments.create( artifact_uid=model_id, name="deployment" )



#######################################################################################

Synchronous deployment creation for uid: '799bde90-b034-49f0-982f-c29e539505a3' started

#######################################################################################


INITIALIZING
DEPLOY_IN_PROGRESS
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='b1f408f0-ac66-4ad3-aba9-f8a6e53825a9'
------------------------------------------------------------------------------------------------




In [50]:
scoring_endpoint = client.deployments.get_scoring_url(model_deployment_details)
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/921b4e0f-5957-4d27-aee4-ebc3a5d70714/deployments/b1f408f0-ac66-4ad3-aba9-f8a6e53825a9/online'

In [51]:
scoring_payload = {"fields": ["Prediction"],"values": ([[0,1,30000,45000,29456,65524,12]])}
predictions = client.deployments.score(scoring_endpoint, scoring_payload)
predictions

{'fields': ['prediction', 'prediction_classes', 'probability'],
 'values': [[[1746645.875], [1], [1746645.875]]]}